server:
  port: 8080

spid:
  entity-id: http://spid-test.local:8080
  assertion-consumer-service-url: http://spid-test.local:8080/spid/acs
  single-logout-service-url: http://spid-test.local:8080/spid/logout
  minimum-level: LEVEL_2
  sign-requests: true
  certificate-path: classpath:spid/cert.pem
  private-key-path: classpath:spid/key.pem

spring:
  thymeleaf:
    cache: false